spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${GCP_PROJECT_ID}:${GCP_REGION}:${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DB_USERNAME:bread}
    password: ${DB_PASSWORD:bread1234}
    driver-class-name: org.postgresql.Driver

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      sql:
        enabled: false

  jpa:
    show-sql: ${SHOW_SQL:false}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:3s}

gcs:
  bucket: ${GCS_BUCKET}

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
