spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME:breaddb}?cloudSqlInstance=${GCP_PROJECT_ID}:${GCP_REGION}:${CLOUD_SQL_INSTANCE}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DB_USERNAME:bread}
    password: ${DB_PASSWORD:bread1234}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}
