steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'be/Dockerfile'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/teambreadbread-breadbread/bread-be:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/teambreadbread-breadbread/bread-be:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bread-be'
      - '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/teambreadbread-breadbread/bread-be:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'

options:
  logging: CLOUD_LOGGING_ONLY
