CREATE TABLE public.bakery_congestion_signal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    bakery_id bigint NOT NULL,
    bakery_name character varying(255),
    congestion_score double precision,
    level character varying(20),
    expected_wait_min integer,
    reason text,
    waiting_keyword_count integer,
    open_run_keyword_count integer,
    sold_out_keyword_count integer,
    recent_mention_count integer,
    morning_mentions integer,
    afternoon_mentions integer,
    evening_mentions integer,
    collected_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT bakery_congestion_signal_level_check CHECK (
        level IN ('LOW', 'MEDIUM', 'HIGH')
    )
);

CREATE INDEX idx_bakery_congestion_signal_bakery_id
    ON public.bakery_congestion_signal (bakery_id);

CREATE INDEX idx_bakery_congestion_signal_collected_at
    ON public.bakery_congestion_signal (collected_at DESC);
