CREATE TABLE public.bakery_trend_tag (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    keyword character varying(100) NOT NULL,
    trend_score double precision,
    trend_status character varying(20),
    growth_rate double precision,
    bakery_id bigint,
    bakery_name character varying(255),
    matched_menus text,
    sources text,
    collected_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT bakery_trend_tag_trend_status_check CHECK (
        trend_status IN ('RISING', 'STABLE', 'FALLING')
    )
);

CREATE INDEX idx_bakery_trend_tag_bakery_id
    ON public.bakery_trend_tag (bakery_id);

CREATE INDEX idx_bakery_trend_tag_collected_at
    ON public.bakery_trend_tag (collected_at DESC);

CREATE INDEX idx_bakery_trend_tag_trend_score
    ON public.bakery_trend_tag (trend_score DESC);
