CREATE TABLE temp_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL UNIQUE,
    object_key VARCHAR(500) NOT NULL UNIQUE,
    domain VARCHAR(30) NOT NULL,
    user_id BIGINT NOT NULL,
    uploaded_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE temp_image
    ADD CONSTRAINT fk_temp_image_user
    FOREIGN KEY (user_id) REFERENCES users(id);

CREATE INDEX idx_temp_image_uploaded_at ON temp_image (uploaded_at);
CREATE INDEX idx_temp_image_user_id ON temp_image (user_id);
CREATE INDEX idx_temp_image_domain ON temp_image (domain);
