CREATE TABLE bakery_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    user_id BIGINT REFERENCES users(id),
    bakery_name VARCHAR(255),
    address VARCHAR(255),
    district VARCHAR(255),
    recommendation VARCHAR(500),
    target_bakery_name VARCHAR(255),
    update_field VARCHAR(50),
    correct_value VARCHAR(500),
    description VARCHAR(500)
);

CREATE TABLE bakery_report_representative_menus (
    bakery_report_id BIGINT NOT NULL REFERENCES bakery_report(id),
    menu VARCHAR(255)
);
