SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bakery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    address character varying(255),
    appearance_time time(6) without time zone,
    closed_day_note character varying(255),
    holiday_closed boolean,
    last_order_time character varying(255),
    weekday_close time(6) without time zone,
    weekday_open time(6) without time zone,
    weekend_close time(6) without time zone,
    weekend_open time(6) without time zone,
    dine_in_available boolean NOT NULL,
    frequency character varying(255),
    latitude double precision,
    longitude double precision,
    map_link character varying(255),
    name character varying(255),
    note character varying(255),
    parking_available boolean NOT NULL,
    phone character varying(255),
    rating double precision,
    region character varying(255),
    owner_id bigint,
    bakery_type character varying(255),
    drink_available boolean NOT NULL,
    CONSTRAINT bakery_bakery_type_check CHECK (((bakery_type)::text = ANY ((ARRAY['CLASSIC'::character varying, 'DESSERT'::character varying, 'K_DESSERT'::character varying, 'GOURMET'::character varying, 'TRENDY'::character varying, 'PLAIN'::character varying])::text[]))),
    CONSTRAINT bakery_frequency_check CHECK (((frequency)::text = ANY ((ARRAY['ALWAYS'::character varying, 'ONCE_PER_DAY'::character varying, 'TWICE_PER_DAY'::character varying])::text[])))
);


--
-- Name: bakery_closed_days; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery_closed_days (
    bakery_id bigint NOT NULL,
    closed_days character varying(255),
    CONSTRAINT bakery_closed_days_closed_days_check CHECK (((closed_days)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: bakery_crowded_days; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery_crowded_days (
    bakery_id bigint NOT NULL,
    crowded_days character varying(255),
    CONSTRAINT bakery_crowded_days_crowded_days_check CHECK (((crowded_days)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: bakery_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bakery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bakery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bakery_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery_image (
    id bigint NOT NULL,
    display_order integer NOT NULL,
    image_url character varying(255),
    bakery_id bigint
);


--
-- Name: bakery_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bakery_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bakery_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bakery_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery_like (
    id bigint NOT NULL,
    bakery_id bigint,
    user_id bigint
);


--
-- Name: bakery_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bakery_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bakery_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bakery_personalities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery_personalities (
    bakery_id bigint NOT NULL,
    bakery_personalities character varying(255),
    CONSTRAINT bakery_personalities_bakery_personalities_check CHECK (((bakery_personalities)::text = ANY ((ARRAY['LANDMARK'::character varying, 'HIDDEN_GEM'::character varying, 'HOT_PLACE'::character varying, 'HERITAGE'::character varying, 'HIP_AND_INDUSTRIAL'::character varying])::text[])))
);


--
-- Name: bakery_use_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bakery_use_types (
    bakery_id bigint NOT NULL,
    bakery_use_types character varying(255),
    CONSTRAINT bakery_use_types_bakery_use_types_check CHECK (((bakery_use_types)::text = ANY ((ARRAY['TAKEOUT'::character varying, 'CAFE_STYLE'::character varying, 'MOODY_SPACE'::character varying, 'PRACTICAL'::character varying])::text[])))
);


--
-- Name: bread; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bread (
    id bigint NOT NULL,
    bread_type character varying(255),
    image_url character varying(255),
    name character varying(255),
    price integer NOT NULL,
    sellout_min integer NOT NULL,
    signature boolean NOT NULL,
    bakery_id bigint,
    estimated_sold_out boolean NOT NULL,
    CONSTRAINT bread_bread_type_check CHECK (((bread_type)::text = ANY ((ARRAY['BREAD'::character varying, 'SANDWICH'::character varying, 'CAKE'::character varying, 'RICE_CAKE'::character varying, 'COOKIE'::character varying, 'DIET'::character varying])::text[])))
);


--
-- Name: bread_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bread ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bread_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content text NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    bakery_count integer,
    budget_range character varying(255),
    drink_preference boolean,
    flexibility_level character varying(255),
    latitude double precision,
    longitude double precision,
    minimize_route boolean,
    travel_type character varying(255),
    waiting_preference boolean,
    course_type character varying(255) NOT NULL,
    estimated_cost bigint,
    estimated_time character varying(255),
    bread_type character varying(255),
    editor_pick boolean,
    region character varying(255),
    theme character varying(255),
    name character varying(255) NOT NULL,
    shared boolean NOT NULL,
    thumbnail_url character varying(255),
    user_id bigint,
    user_preference_id bigint,
    recommend_reason character varying(255),
    summary character varying(255),
    CONSTRAINT course_bread_type_check CHECK (((bread_type)::text = ANY ((ARRAY['BREAD'::character varying, 'SANDWICH'::character varying, 'CAKE'::character varying, 'RICE_CAKE'::character varying, 'COOKIE'::character varying, 'DIET'::character varying])::text[]))),
    CONSTRAINT course_budget_range_check CHECK (((budget_range)::text = ANY ((ARRAY['UNDER_20000'::character varying, 'BETWEEN_20000_40000'::character varying, 'OVER_40000'::character varying, 'ANY'::character varying])::text[]))),
    CONSTRAINT course_course_type_check CHECK (((course_type)::text = ANY ((ARRAY['MANUAL'::character varying, 'AI'::character varying])::text[]))),
    CONSTRAINT course_flexibility_level_check CHECK (((flexibility_level)::text = ANY ((ARRAY['MAINTAIN'::character varying, 'ACTIVE'::character varying, 'SOLDOUT_ONLY'::character varying])::text[]))),
    CONSTRAINT course_travel_type_check CHECK (((travel_type)::text = ANY ((ARRAY['ALONE'::character varying, 'COUPLE'::character varying, 'FRIENDS'::character varying, 'FAMILY'::character varying])::text[])))
);


--
-- Name: course_bakery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_bakery (
    id bigint NOT NULL,
    reason character varying(255),
    visit_order integer NOT NULL,
    bakery_id bigint,
    course_id bigint,
    recommended_bread character varying(255)
);


--
-- Name: course_bakery_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_bakery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_bakery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_like (
    id bigint NOT NULL,
    course_id bigint,
    user_id bigint
);


--
-- Name: course_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_preferred_bread_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_preferred_bread_types (
    course_id bigint NOT NULL,
    preferred_bread_types character varying(255),
    CONSTRAINT course_preferred_bread_types_preferred_bread_types_check CHECK (((preferred_bread_types)::text = ANY ((ARRAY['BREAD'::character varying, 'SANDWICH'::character varying, 'CAKE'::character varying, 'RICE_CAKE'::character varying, 'COOKIE'::character varying, 'DIET'::character varying])::text[])))
);


--
-- Name: crowd_time; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crowd_time (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    crowd_level character varying(255),
    day_type character varying(255),
    expected_wait_min integer,
    peak_end time(6) without time zone,
    peak_start time(6) without time zone,
    source_type character varying(255),
    bakery_id bigint,
    CONSTRAINT crowd_time_crowd_level_check CHECK (((crowd_level)::text = ANY ((ARRAY['LOW'::character varying, 'MIDDLE'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT crowd_time_day_type_check CHECK (((day_type)::text = ANY ((ARRAY['WEEKDAY'::character varying, 'WEEKEND'::character varying])::text[])))
);


--
-- Name: crowd_time_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.crowd_time ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crowd_time_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    cancelled_at timestamp(6) without time zone,
    discount_amount bigint NOT NULL,
    fail_reason character varying(255),
    final_amount bigint NOT NULL,
    original_amount bigint NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_id character varying(255) NOT NULL,
    payment_method character varying(255) NOT NULL,
    payment_method_detail character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_transaction_id character varying(255),
    refunded_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    reservation_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT payment_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CARD'::character varying, 'TRANSFER'::character varying, 'VIRTUAL_ACCOUNT'::character varying, 'MOBILE'::character varying, 'EASY_PAY'::character varying, 'GIFT_CERTIFICATE'::character varying])::text[]))),
    CONSTRAINT payment_payment_method_detail_check CHECK (((payment_method_detail)::text = ANY ((ARRAY['NAVER_PAY'::character varying, 'KAKAO_PAY'::character varying, 'TOSS_PAY'::character varying, 'CARD'::character varying, 'BANK_TRANSFER'::character varying, 'MOBILE'::character varying])::text[]))),
    CONSTRAINT payment_pg_provider_check CHECK (((pg_provider)::text = 'TOSS_PAYMENT'::text)),
    CONSTRAINT payment_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'PAY_PENDING'::character varying, 'VIRTUAL_ACCOUNT_ISSUED'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phone_verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phone_verification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    auth_type character varying(255),
    code character varying(255),
    expired_at timestamp(6) without time zone,
    phone character varying(255),
    purpose character varying(255),
    verification_token character varying(255),
    verified boolean NOT NULL,
    CONSTRAINT phone_verification_auth_type_check CHECK (((auth_type)::text = ANY ((ARRAY['SMS'::character varying, 'PASS'::character varying])::text[]))),
    CONSTRAINT phone_verification_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['SIGNUP'::character varying, 'FIND_ID'::character varying, 'FIND_PW'::character varying])::text[])))
);


--
-- Name: phone_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phone_verification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content text NOT NULL,
    post_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT post_post_type_check CHECK (((post_type)::text = ANY ((ARRAY['NOTICE'::character varying, 'FREE'::character varying, 'ARTICLE'::character varying])::text[])))
);


--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_image_urls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_image_urls (
    post_id bigint NOT NULL,
    image_url character varying(255) NOT NULL
);


--
-- Name: post_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_like (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: post_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    expired_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(500) NOT NULL,
    user_id bigint
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservation (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    cancelled_at timestamp(6) without time zone,
    course_name_snapshot character varying(255),
    departure character varying(255),
    departure_date date,
    departure_lat double precision,
    departure_lng double precision,
    departure_time time(6) without time zone,
    head_count integer NOT NULL,
    quoted_amount bigint,
    status character varying(255),
    course_id bigint,
    user_id bigint,
    confirmed_at timestamp(6) without time zone,
    CONSTRAINT reservation_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content character varying(300),
    image_url character varying(255),
    rating integer NOT NULL,
    bakery_id bigint,
    user_id bigint,
    CONSTRAINT review_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);


--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_image (
    review_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: route; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.route (
    id bigint NOT NULL,
    course_id bigint,
    user_id bigint
);


--
-- Name: route_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.route ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sso_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sso_account (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    user_id bigint,
    CONSTRAINT sso_account_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying])::text[])))
);


--
-- Name: sso_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sso_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sso_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_bakery_moods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_bakery_moods (
    preference_id bigint NOT NULL,
    bakery_moods character varying(255),
    CONSTRAINT user_bakery_moods_bakery_moods_check CHECK (
  ((bakery_moods)::text = ANY (
    (
      ARRAY[
        'LANDMARK'::character varying,
        'HIDDEN_GEM'::character varying,
        'HOT_PLACE'::character varying,
        'HERITAGE'::character varying,
        'HIP_AND_INDUSTRIAL'::character varying
      ]
    )::text[]
  ))
)
);


--
-- Name: user_bakery_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_bakery_types (
    preference_id bigint NOT NULL,
    bakery_types character varying(255),
    CONSTRAINT user_bakery_types_bakery_types_check CHECK (((bakery_types)::text = ANY ((ARRAY['CLASSIC'::character varying, 'DESSERT'::character varying, 'K_DESSERT'::character varying, 'GOURMET'::character varying, 'TRENDY'::character varying, 'PLAIN'::character varying])::text[])))
);


--
-- Name: user_bread_styles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_bread_styles (
    preference_id bigint NOT NULL,
    bread_styles character varying(255),
    bread_types character varying(255),
    CONSTRAINT user_bread_styles_bread_styles_check CHECK (((bread_styles)::text = ANY ((ARRAY['PLAIN'::character varying, 'DESSERT'::character varying, 'PREMIUM'::character varying, 'TRADITIONAL'::character varying, 'TRENDY'::character varying])::text[]))),
    CONSTRAINT user_bread_styles_bread_types_check CHECK (((bread_types)::text = ANY ((ARRAY['CLASSIC'::character varying, 'DESSERT'::character varying, 'K_DESSERT'::character varying, 'GOURMET'::character varying, 'TRENDY'::character varying, 'PLAIN'::character varying])::text[])))
);


--
-- Name: user_preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preference (
    id bigint NOT NULL,
    waiting_tolerance character varying(255),
    user_id bigint,
    CONSTRAINT user_preference_waiting_tolerance_check CHECK (((waiting_tolerance)::text = ANY ((ARRAY['NO_WAIT'::character varying, 'UNDER_20'::character varying, 'UNDER_30'::character varying, 'ANYTIME'::character varying])::text[])))
);


--
-- Name: user_preference_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_use_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_use_types (
    preference_id bigint NOT NULL,
    bakery_use_types character varying(255),
    CONSTRAINT user_use_types_bakery_use_types_check CHECK (((bakery_use_types)::text = ANY (ARRAY['TAKEOUT'::text, 'CAFE_STYLE'::text, 'MOODY_SPACE'::text, 'PRACTICAL'::text])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    active boolean NOT NULL,
    email character varying(255),
    grade character varying(255),
    login_id character varying(255),
    name character varying(255) NOT NULL,
    nickname character varying(255),
    password character varying(255),
    phone character varying(255),
    privacy_agreed boolean NOT NULL,
    role character varying(255) NOT NULL,
    telecom character varying(255),
    terms_agreed boolean NOT NULL,
    usage_count integer NOT NULL,
    profile_image_url character varying(255),
    CONSTRAINT users_grade_check CHECK (((grade)::text = ANY ((ARRAY['MORNING_BREAD'::character varying, 'CREAM_BREAD'::character varying, 'SALT_BREAD'::character varying, 'GOLDEN_CHOUX'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying, 'ROLE_BUSINESS'::character varying, 'ROLE_DRIVER'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bakery_image bakery_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_image
    ADD CONSTRAINT bakery_image_pkey PRIMARY KEY (id);


--
-- Name: bakery_like bakery_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_like
    ADD CONSTRAINT bakery_like_pkey PRIMARY KEY (id);


--
-- Name: bakery bakery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery
    ADD CONSTRAINT bakery_pkey PRIMARY KEY (id);


--
-- Name: bread bread_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bread
    ADD CONSTRAINT bread_pkey PRIMARY KEY (id);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: course_bakery course_bakery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_bakery
    ADD CONSTRAINT course_bakery_pkey PRIMARY KEY (id);


--
-- Name: course_like course_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_like
    ADD CONSTRAINT course_like_pkey PRIMARY KEY (id);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: crowd_time crowd_time_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crowd_time
    ADD CONSTRAINT crowd_time_pkey PRIMARY KEY (id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: phone_verification phone_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verification
    ADD CONSTRAINT phone_verification_pkey PRIMARY KEY (id);


--
-- Name: post_like post_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT post_like_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: route route_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT route_pkey PRIMARY KEY (id);


--
-- Name: sso_account sso_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sso_account
    ADD CONSTRAINT sso_account_pkey PRIMARY KEY (id);


--
-- Name: bakery uk66mk0u038yco568o2tec5logt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery
    ADD CONSTRAINT uk66mk0u038yco568o2tec5logt UNIQUE (owner_id);


--
-- Name: sso_account uk9tye4i29osilr2sst14ctpkcd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sso_account
    ADD CONSTRAINT uk9tye4i29osilr2sst14ctpkcd UNIQUE (provider, provider_user_id);


--
-- Name: payment ukh2cx18159w1evkp50cj9p8s8y; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT ukh2cx18159w1evkp50cj9p8s8y UNIQUE (payment_id);


--
-- Name: course_like ukhdkgda6399ncaq5rbjdp5ad6p; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_like
    ADD CONSTRAINT ukhdkgda6399ncaq5rbjdp5ad6p UNIQUE (course_id, user_id);


--
-- Name: users uki3xs7wmfu2i3jt079uuetycit; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uki3xs7wmfu2i3jt079uuetycit UNIQUE (login_id);


--
-- Name: route ukp2uobaj2qqbk5v2sm4jfh73g5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT ukp2uobaj2qqbk5v2sm4jfh73g5 UNIQUE (course_id, user_id);


--
-- Name: post_like ukpmmko3h7yonaqhy5gxvnmdeue; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT ukpmmko3h7yonaqhy5gxvnmdeue UNIQUE (post_id, user_id);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: user_preference uks5oeayykfc7bpkpdwyrffwcqx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT uks5oeayykfc7bpkpdwyrffwcqx UNIQUE (user_id);


--
-- Name: bakery_like ukwit00g0fnk1yrf1r32cvfyv7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_like
    ADD CONSTRAINT ukwit00g0fnk1yrf1r32cvfyv7 UNIQUE (bakery_id, user_id);


--
-- Name: user_preference user_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT user_preference_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: review_image fk16wp089tx9nm0obc217gvdd6l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT fk16wp089tx9nm0obc217gvdd6l FOREIGN KEY (review_id) REFERENCES public.review(id);


--
-- Name: bakery_crowded_days fk1obg7vfwltrk57drhh558hg52; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_crowded_days
    ADD CONSTRAINT fk1obg7vfwltrk57drhh558hg52 FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: route fk1vc6g7e02vvijsniyf4x114x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT fk1vc6g7e02vvijsniyf4x114x FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: course fk2nmcqx8d89xeticql10qxxvdl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fk2nmcqx8d89xeticql10qxxvdl FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bakery fk3xtjblnmmt3mh7jadbfegy9qw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery
    ADD CONSTRAINT fk3xtjblnmmt3mh7jadbfegy9qw FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: bakery_closed_days fk40eab5blhfefwt26oigjd60k3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_closed_days
    ADD CONSTRAINT fk40eab5blhfefwt26oigjd60k3 FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: course_bakery fk5e00ed37n6it1cqvdtj117baf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_bakery
    ADD CONSTRAINT fk5e00ed37n6it1cqvdtj117baf FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: course_preferred_bread_types fk5fuh93geo29is4sj7nlmwuhj4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_preferred_bread_types
    ADD CONSTRAINT fk5fuh93geo29is4sj7nlmwuhj4 FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: review fk6cpw2nlklblpvc7hyt7ko6v3e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk6cpw2nlklblpvc7hyt7ko6v3e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bakery_like fk6qgjykscbgojyrqy49bb6sni9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_like
    ADD CONSTRAINT fk6qgjykscbgojyrqy49bb6sni9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: reservation fk70xvcg3ukkffy7v2fc43femq3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk70xvcg3ukkffy7v2fc43femq3 FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: post fk7ky67sgi7k0ayf22652f7763r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk7ky67sgi7k0ayf22652f7763r FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_preference fk7mgxw6j2m7uvuk3svr9vsar8p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT fk7mgxw6j2m7uvuk3svr9vsar8p FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bakery_use_types fkabtuskbdbj6ly7wsb63cw84hk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_use_types
    ADD CONSTRAINT fkabtuskbdbj6ly7wsb63cw84hk FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: bakery_image fkac2suptw9l0yetinawmcjpque; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_image
    ADD CONSTRAINT fkac2suptw9l0yetinawmcjpque FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: bakery_like fkc0p11t120vlufgff3jq68cxg6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_like
    ADD CONSTRAINT fkc0p11t120vlufgff3jq68cxg6 FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: bread fkfogc8ido9eiwganh7vs4c45sc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bread
    ADD CONSTRAINT fkfogc8ido9eiwganh7vs4c45sc FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: user_bread_styles fkg3fbwgy1reb5wvvtc8l7i86a4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_bread_styles
    ADD CONSTRAINT fkg3fbwgy1reb5wvvtc8l7i86a4 FOREIGN KEY (preference_id) REFERENCES public.user_preference(id);


--
-- Name: course_like fkigolehlcjkfbvskla7u488so5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_like
    ADD CONSTRAINT fkigolehlcjkfbvskla7u488so5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: post_like fkijnjmw0imnatadr3agtk0udip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fkijnjmw0imnatadr3agtk0udip FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: crowd_time fkimb1dphwdhxmdr8o6q1364xpi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crowd_time
    ADD CONSTRAINT fkimb1dphwdhxmdr8o6q1364xpi FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: post_like fkj7iy0k7n3d0vkh8o7ibjna884; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fkj7iy0k7n3d0vkh8o7ibjna884 FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: course_like fkjd7ruc1j8inlytwvu8mfis949; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_like
    ADD CONSTRAINT fkjd7ruc1j8inlytwvu8mfis949 FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- Name: user_bakery_moods fkjtwl7qkqfa3v8oj8a0sebo36h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_bakery_moods
    ADD CONSTRAINT fkjtwl7qkqfa3v8oj8a0sebo36h FOREIGN KEY (preference_id) REFERENCES public.user_preference(id);


--
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: review fkl4t7vnn2bqf00geuyurl1g342; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkl4t7vnn2bqf00geuyurl1g342 FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: user_bakery_types fkm5oqnw9pcukt8u6vyp1atkgfx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_bakery_types
    ADD CONSTRAINT fkm5oqnw9pcukt8u6vyp1atkgfx FOREIGN KEY (preference_id) REFERENCES public.user_preference(id);


--
-- Name: sso_account fkma4j4mlgaxp7y9g2v4tjjmgrb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sso_account
    ADD CONSTRAINT fkma4j4mlgaxp7y9g2v4tjjmgrb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payment fkmi2669nkjesvp7cd257fptl6f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkmi2669nkjesvp7cd257fptl6f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: route fkmnuaqyw0fgfusrgfg2628uo25; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route
    ADD CONSTRAINT fkmnuaqyw0fgfusrgfg2628uo25 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: course_bakery fkne6svlc9tcs7var6tjfq8sxss; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_bakery
    ADD CONSTRAINT fkne6svlc9tcs7var6tjfq8sxss FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);


--
-- Name: user_use_types fkoa8g0lao2acp75a06ffqvf0qj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_use_types
    ADD CONSTRAINT fkoa8g0lao2acp75a06ffqvf0qj FOREIGN KEY (preference_id) REFERENCES public.user_preference(id);


--
-- Name: comment fkqm52p1v3o13hy268he0wcngr5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkqm52p1v3o13hy268he0wcngr5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: course fkqqe195chhpjmp3kcr079qkklh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT fkqqe195chhpjmp3kcr079qkklh FOREIGN KEY (user_preference_id) REFERENCES public.user_preference(id);


--
-- Name: reservation fkrea93581tgkq61mdl13hehami; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkrea93581tgkq61mdl13hehami FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payment fkrewpj5f9v9xehy4ga8g221nw1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkrewpj5f9v9xehy4ga8g221nw1 FOREIGN KEY (reservation_id) REFERENCES public.reservation(id);


--
-- Name: comment fks1slvnkuemjsq2kj4h3vhx7i1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fks1slvnkuemjsq2kj4h3vhx7i1 FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: post_image_urls fktnoxku4ecn636e83998rvsoy8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_image_urls
    ADD CONSTRAINT fktnoxku4ecn636e83998rvsoy8 FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: bakery_personalities fku303604qimlit2yafeo4f11m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bakery_personalities
    ADD CONSTRAINT fku303604qimlit2yafeo4f11m FOREIGN KEY (bakery_id) REFERENCES public.bakery(id);
