/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RecommendationRouteImport } from "./routes/recommendation";
import { Route as PreferenceRouteImport } from "./routes/preference";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AiSearchResultRouteImport } from "./routes/ai-search-result";
import { Route as IndexRouteImport } from "./routes/index";

const RecommendationRoute = RecommendationRouteImport.update({
  id: "/recommendation",
  path: "/recommendation",
  getParentRoute: () => rootRouteImport,
} as any);
const PreferenceRoute = PreferenceRouteImport.update({
  id: "/preference",
  path: "/preference",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AiSearchResultRoute = AiSearchResultRouteImport.update({
  id: "/ai-search-result",
  path: "/ai-search-result",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/ai-search-result": typeof AiSearchResultRoute;
  "/login": typeof LoginRoute;
  "/preference": typeof PreferenceRoute;
  "/recommendation": typeof RecommendationRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/ai-search-result": typeof AiSearchResultRoute;
  "/login": typeof LoginRoute;
  "/preference": typeof PreferenceRoute;
  "/recommendation": typeof RecommendationRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/ai-search-result": typeof AiSearchResultRoute;
  "/login": typeof LoginRoute;
  "/preference": typeof PreferenceRoute;
  "/recommendation": typeof RecommendationRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/ai-search-result" | "/login" | "/preference" | "/recommendation";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/ai-search-result" | "/login" | "/preference" | "/recommendation";
  id: "__root__" | "/" | "/ai-search-result" | "/login" | "/preference" | "/recommendation";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AiSearchResultRoute: typeof AiSearchResultRoute;
  LoginRoute: typeof LoginRoute;
  PreferenceRoute: typeof PreferenceRoute;
  RecommendationRoute: typeof RecommendationRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/recommendation": {
      id: "/recommendation";
      path: "/recommendation";
      fullPath: "/recommendation";
      preLoaderRoute: typeof RecommendationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/preference": {
      id: "/preference";
      path: "/preference";
      fullPath: "/preference";
      preLoaderRoute: typeof PreferenceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ai-search-result": {
      id: "/ai-search-result";
      path: "/ai-search-result";
      fullPath: "/ai-search-result";
      preLoaderRoute: typeof AiSearchResultRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSearchResultRoute: AiSearchResultRoute,
  LoginRoute: LoginRoute,
  PreferenceRoute: PreferenceRoute,
  RecommendationRoute: RecommendationRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
